<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_JakBar</name>
   <tag></tag>
   <elementGuidId>2be1c651-f983-4972-a593-3ba7b876d512</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cityAndProvince']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cityAndProvince</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03bf5e21-c866-45af-a5c6-ec45eebb1dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>143359b5-4ae2-4350-9046-7a144812720a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>autocomplete__field_vc5UL autocomplete__field--has-error_auuvI</value>
      <webElementGuid>1a10edbc-6cf0-4360-a612-cca5d3ec9e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cityAndProvince</value>
      <webElementGuid>454d9878-e7bb-4647-b84e-72aef1a5d0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cityAndProvince</value>
      <webElementGuid>97e8638c-5bd5-468b-8059-b0e707dfae25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Kabupaten/Kota</value>
      <webElementGuid>a8038cb4-ae20-4801-93d6-2e96f060da51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53b832b9-8118-4e0c-9a13-4c77b7612bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>KOTA JAKARTA BARAT</value>
      <webElementGuid>7caab832-bb97-47e0-9b87-307f5a922036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cityAndProvince&quot;)</value>
      <webElementGuid>2ae48dae-76b3-45b6-a8d0-71cfe0565f29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cityAndProvince']</value>
      <webElementGuid>08a06af1-90e0-4c42-844e-62e2f9ba3a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='safe-area']/div[2]/div[2]/div/div[6]/div/input</value>
      <webElementGuid>759a5d53-d2ab-4450-8135-a9107c6bcdb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>5e0fa364-d0de-49fc-bef8-d9d181bfcfb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cityAndProvince' and @name = 'cityAndProvince' and @placeholder = 'Pilih Kabupaten/Kota' and @type = 'text']</value>
      <webElementGuid>30856731-9ffd-41c2-af26-dc69ad9cfbb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
