<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_pilihVerifikasi</name>
   <tag></tag>
   <elementGuidId>0e1a9fa6-a636-474c-9d89-7213275057e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='safe-area']/div[2]/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.header_2xOrt.AppHeader_card__header-title__9bScY.mx-auto.text-color-gray-dark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>0bbe7124-1e1f-46f0-88a4-c71b6cbd72fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header_2xOrt AppHeader_card__header-title__9bScY mx-auto text-color-gray-dark</value>
      <webElementGuid>c96d72ae-2ba5-435c-8905-a5d58fe3fb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Metode Verifikasi</value>
      <webElementGuid>e33c8b2f-469e-4d5a-bd51-f5a776c1758c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;safe-area&quot;)/div[2]/div[@class=&quot;superapp-container AppHeader_container__gY16K&quot;]/div[@class=&quot;AppHeader_card__hPYXS background-primary&quot;]/h1[@class=&quot;header_2xOrt AppHeader_card__header-title__9bScY mx-auto text-color-gray-dark&quot;]</value>
      <webElementGuid>dfe2373e-ee29-4727-a0ab-a0ec1fd80020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='safe-area']/div[2]/div/div/h1</value>
      <webElementGuid>7bcbb523-70e2-4462-991f-3fa8ac9419e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih metode verifikasi untuk mengirim kode OTP'])[1]/preceding::h1[1]</value>
      <webElementGuid>1786ad62-90f2-402f-86b7-bad85036b3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::h1[1]</value>
      <webElementGuid>b73b570a-844a-4263-8359-9576ef49d0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih Metode Verifikasi']/parent::*</value>
      <webElementGuid>a173bed8-2f82-4842-8671-c8452c09ef4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>301714b9-c9d8-4433-bd50-d6e0b64eaca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Pilih Metode Verifikasi' or . = 'Pilih Metode Verifikasi')]</value>
      <webElementGuid>193ff0f8-8ab0-4700-8742-0bea74b8b8cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
